version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon
    - Juha_Fagerstedt_Resume_Master.pdf
    - styles/main.css
    - images/*
